project:
  type: website
  output-dir: docs

website:
  title: "website_title"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

