project:
  type: website
  output-dir: docs

website:
  title: "視覺化課程"
  navbar: 
    search: true
     
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: "Noto Sans TC"

editor: visual

